### ISSUE TITLE
@ShiehShieh 求修复前端 全毁了

### ISSUE THREAD

**Issue by blackbbc** [TJUSSE/sse_subscription#1]

**Comment by ShiehShieh** [comment]
What happened?

**Comment by breezewish** [comment]
需要将订阅部分样式迁移到 0.0.2 中
迁移的时候注意遵循 SMACSS，和尽量保持：
- 短选择器层数（不宜层数过多，能用一层就一层）
- 不污染其他样式（遵循一个好的命名规范就可以避免）
  以上两条具体实例可参考 0.0.2 下 Page 里其他几个样式

**Comment by breezewish** [comment]
已拆分为几个具体的 issue。
Closed
