### ISSUE TITLE
发送邮件过程没有验证是否发送成功

### ISSUE THREAD

**Issue by breezewish** [TJUSSE/sse_subscription#5]
目前无论加入发送队列成功与否，前端都显示邮件已发送。
- 在后端，需要对成功发送的情况返回成功状态，对于失败的状态返回失败状态
- 在前端，需要对于失败状态告知用户，如类似于「验证邮件发送失败，目前订阅服务暂时不可用，请立即告知我们这个问题」

**Comment by breezewish** [comment]
assign to @blackbbc @ShiehShieh

**Comment by blackbbc** [comment]
@SummerWish 
该如何从队列里取回任务的执行情况呢

**Comment by breezewish** [comment]
可以先假定放进队列里一定会成功
主要是前端部分需要对于后端连队列都没放进去的情况做出提示

**Comment by breezewish** [comment]
Fixed in https://github.com/TJUSSE/sseweb-theme/commit/eac6b48807d0b6cf3360fa9898602db7e1abd4d4
